### PR TITLE
Feature/edi 197 add addsequence to editframe js

### PR DESCRIPTION
**Pull request by alittlebitweird**
###Composition
* adds `getLayerAttribute` method to allow layer-classes to access layer attributes
* add `updateFile` and `getMetadata` methods to enable input file `magic` via `processCompositionFile`, which allows user to provide a local path, a url, or a read stream for any input
* adds `addSequence` method which allows user to pass previously created layers and concatenate them
* downloads from url and associated file management cleanup is all done on encode instead of on a file by file basis

### Sequence
* adds `Sequence` class that gets returned by `composition.addSequence`, which has a `setStart` method which adjusts `start` position of all child layers

### Videos
* updates `new` method to ustilize aforementioned `file magic` 

### Validation
* process exiting on failed validation is now skipped during tests for ease-of-debugging

### Mocks
* adds defaults to mocks to reduce boilerplate in tests

### CODE REVIEW

**Review by brycedev — CHANGES_REQUESTED** [review]
@alittlebitweird would it be possible to also exclude duration if a sequence is added? 

in my testing, i'm adding a sequence, and the output is longer than the specified composition duration; it would be nice to be able to run the encode without including a duration

**Comment by alittlebitweird** [comment]
> @alittlebitweird would it be possible to also exclude duration if a sequence is added?
> 
> in my testing, i'm adding a sequence, and the output is longer than the specified composition duration; it would be nice to be able to run the encode without including a duration

I was thinking about that too. I don't think we can do it via typescript but we can def do it with runtime checks 👍🏻

**Comment by brycedev** [comment]
> I was thinking about that too. I don't think we can do it via typescript but we can def do it with runtime checks 👍🏻

cool cool. given that, do you think it makes sense for the composition duration to override the sequenced output duration, if the global duration is provided?

**Comment by alittlebitweird** [comment]
Gotta think about this one

**Pull request merged**
