### PR TITLE
add custom composition fps support [EDI-902]

### PR DESCRIPTION
**Pull request by IliasHad**

### CODE REVIEW

**Comment by IliasHad** [comment]
@brycedev  run has been failed because I should merge the shared types lib first

**Comment by brycedev** [comment]
let's bump shared-types to 3.11.0 now

**Review by brycedev — CHANGES_REQUESTED** [review]
let's default this to 30, vs 29.97. we're going to move to 30 elsewhere as well

**Comment by IliasHad** [comment]
@brycedev  updated

**Review by brycedev — APPROVED** [review]

**Pull request merged**
