### PR TITLE
feat: add tailwindcss filed to text layer [EDI-860]

### PR DESCRIPTION
**Pull request by IliasHad**

### CODE REVIEW

**Comment by IliasHad** [comment]
@brycedev  We should publish the shared types first to NPM for tailwindcss field to pass the PR build

**Comment by brycedev** [comment]
@IliasHad what are your thoughts on using just "tailwind" as the key name vs "tailwindCss"

**Comment by IliasHad** [comment]
@brycedev  Sounds good to me, I was looking for your feedback about it because I wasn't that happy with it

**Review by brycedev — APPROVED** [review]

**Comment by brycedev** [comment]
@IliasHad ready to bump version

**Pull request merged**
