### PR TITLE
fix: add typedoc

### PR DESCRIPTION
**Pull request by alittlebitweird**

### CODE REVIEW

**Comment by alittlebitweird** [comment]
@brycedev custom table of contents and theming is no longer supported. 

@jyudkin1 can you confirm that `UA-116480461-1` is still the correct google analytics id to use for this?

**Comment by brycedev** [comment]
UA-116480461-1

> @brycedev custom table of contents and theming is no longer supported.
> 
> @jyudkin1 can you confirm that `UA-116480461-1` is still the correct google analytics id to use for this?

@alittlebitweird it's correct

**Comment by jyudkin1** [comment]
> 

its correct.

**Comment by brycedev** [comment]
@alittlebitweird do you mind doing the build and deploy via github actions instead of publishing the /docs? 

few resources: 

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow

https://github.com/actions/upload-pages-artifact

**Pull request merged**
