### PR TITLE
feat: use @editframe/shared-types for filters/lottie types

### PR DESCRIPTION
**Pull request by alittlebitweird**
* adds `@editframe/shared-types` dev-dependency

### CODE REVIEW

**Comment by JonoAugustine** [comment]
Will this still compile in client projects if the type library is private?

**Comment by alittlebitweird** [comment]
> Will this still compile in client projects if the type library is private?

Great question. When I tested locally it worked but I'll double check

**Review by brycedev — APPROVED** [review]
so good!

**Comment by alittlebitweird** [comment]
> Will this still compile in client projects if the type library is private?

just checked with the rapchat app, it does work

**Pull request merged**
