### PR TITLE
feat: add transitions

### PR DESCRIPTION
**Pull request by alittlebitweird**
### Example:

```typescript
  const video1 = await composition.addVideo(
    "https://efapisplat.nyc3.digitaloceanspaces.com/docs/add-sequence/doge-short.mp4"
  );

  const video2 = await composition.addVideo(
    "https://efapisplat.nyc3.digitaloceanspaces.com/docs/add-sequence/drone-lagoon-short.mp4"
  );

  const video3 = await composition.addVideo(
    "https://efapisplat.nyc3.digitaloceanspaces.com/docs/add-sequence/fire-short.mp4"
  );

  const video4 = await composition.addVideo(
    "https://efapisplat.nyc3.digitaloceanspaces.com/docs/add-sequence/doge-short.mp4"
  );

  video1.addTransition({
    duration: 1,
    type: "fadeIn",
  });

  video1.addTransition({
    duration: 1,
    type: "fadeOut",
  });

  video2.addTransition({
    duration: 1,
    type: "fadeIn",
  });

  video2.addTransition({
    duration: 1,
    type: "crossfadeOut",
  });

  video4.addTransition({
    duration: 1,
    type: "crossfadeIn",
  });

  await composition.addSequence([video1, video2, video3, video4]);

```

### Output

https://user-images.githubusercontent.com/4702409/170148325-2c93ffaf-e985-4ec0-bee8-7b5f42d43e3e.mp4

### CODE REVIEW

**Comment by ptrkcsk** [comment]
@alittlebitweird are you able to run the tests locally? most fail for me. here's what i did:

in `shared-types/` :

```
git switch feature/edi-346-add-transitions-to-shared-types
```

in `editframe-js` :

```
git switch feature/edi-345-add-transitions-to-editframe-js
yarn install
yarn link @editframe/shared-types
yarn run test
```

**Comment by alittlebitweird** [comment]
> @alittlebitweird are you able to run the tests locally? most fail for me. here's what i did:
> 
> in `shared-types/` :
> 
> ```shell
> git switch feature/edi-346-add-transitions-to-shared-types
> ```
> 
> in `editframe-js` :
> 
> ```shell
> git switch feature/edi-345-add-transitions-to-editframe-js
> yarn install
> yarn link @editframe/shared-types
> yarn run test
> ```
> 
> CleanShot 2022-05-24 at 19 35 11@2x

hm. i was able to, but this gives me pause so i'll reset everything and try again real quick

**Comment by alittlebitweird** [comment]
> > @alittlebitweird are you able to run the tests locally? most fail for me. here's what i did:
> > in `shared-types/` :
> > ```shell
> > git switch feature/edi-346-add-transitions-to-shared-types
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in `editframe-js` :
> > ```shell
> > git switch feature/edi-345-add-transitions-to-editframe-js
> > yarn install
> > yarn link @editframe/shared-types
> > yarn run test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > CleanShot 2022-05-24 at 19 35 11@2x
> 
> hm. i was able to, but this gives me pause so i'll reset everything and try again real quick

it does still work for me. Did you run `yarn build` in `@editframe/shared-types`?

**Comment by ptrkcsk** [comment]
i'm seeing a similar problem on `dev`, though not as many tests fail:

```sh
git switch dev
git fetch
git pull
rm -fr node_modules
yarn install
yarn run test
```

CleanShot 2022-05-24 at 19 55 12@2x

**Comment by alittlebitweird** [comment]
> 

trying again

**Comment by alittlebitweird** [comment]
> > 
> 
> trying again

yeah all pass for me. weird. let's pair on this tomorrow morning

**Comment by ptrkcsk** [comment]
for future generations, this was fixed by running:

```sh
rm -fr dist
yarn run test
```

we'll modify the `build` script to remove `dist/` before compiling

**Review by ptrkcsk — APPROVED** [review]
Meme Reaction - kcOhcdEAImAJinKlbO

**Pull request merged**
